version: "3.9"

services:

  containerflow:
    image: shubham22121/containerflow:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9999:9999
    depends_on:
      - mongo
    volumes:
      - ./:/app
    environment:
      - MONGO_USER=shubham
      - MONGO_PASSWORD=mypassword

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shubham
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

  nginx:
    image: nginx
    volumes:
      - ./ngnix/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - containerflow

volumes:
  mongo-db: