version: '3.4'

services:
  devopsapp:
    image: shubham22121/devopsapp:v1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9999:9999
    env_file:
      - .env
    volumes:
      - .:/app

  devopsmongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  devopsnginx:
    image: nginx
    volumes:
      - ./ngnix/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - devopsapp



volumes:
  mongo-data: