apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      containers:
      - name: devopsapp
        image: shubham22121/devopsapp:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 9999
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/"

---
# loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: devopsapp
spec:
  type: LoadBalancer
  selector:
    app: devopsapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999



---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devopsmongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: devopsmongo

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017

